from fpdf import FPDF
import datetime

class AirfoilReport(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 15)
        self.cell(0, 10, 'NACA Airfoil Kit Pro - Technical Report', 0, 1, 'C')
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()} | Generated by Manus AI', 0, 0, 'C')

def generate_pdf_report(filename, data):
    pdf = AirfoilReport()
    pdf.add_page()
    pdf.set_font('Arial', '', 12)
    
    # Metadata
    pdf.set_fill_color(240, 240, 240)
    pdf.cell(0, 10, f"Date: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", 0, 1, 'L', fill=True)
    pdf.cell(0, 10, f"Airfoil: {data['name']}", 0, 1, 'L')
    pdf.ln(5)
    
    # Parameters
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 10, "Input Parameters", 0, 1, 'L')
    pdf.set_font('Arial', '', 11)
    for k, v in data['params'].items():
        pdf.cell(0, 8, f"- {k}: {v}", 0, 1, 'L')
    pdf.ln(5)
    
    # Results
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 10, "Aerodynamic Results", 0, 1, 'L')
    pdf.set_font('Arial', '', 11)
    pdf.cell(0, 8, f"Lift Coefficient (Cl): {data['cl']:.4f}", 0, 1, 'L')
    pdf.cell(0, 8, f"Drag Coefficient (Cd): {data['cd']:.4f}", 0, 1, 'L')
    pdf.cell(0, 8, f"L/D Ratio: {data['cl']/data['cd']:.2f}" if data['cd'] != 0 else "L/D: N/A", 0, 1, 'L')
    
    # Plot Image
    if 'plot_path' in data:
        pdf.ln(10)
        pdf.image(data['plot_path'], x=10, w=190)
        
    pdf.output(filename)
